### PR TITLE
ffmpeg: Detect and fail on software decoder fallback

### PR DESCRIPTION
**Pull request by ndufresne**
The goal of fluster is to test one specific implementation, allowing software fallback hides possible integration issues.

### CODE REVIEW

**Comment by rgonzalezfluendo** [comment]
Ohh, Thanks you!

offtopic: In my non-priority TODO list for FFMpeg I had implementing `--no-fallback`.

**Review by rgonzalezfluendo — APPROVED** [review]

**Review by rgonzalezfluendo — CHANGES_REQUESTED** [review]
Sorry, `make format` is missing.

`pre-commit install` to avoid this in the future.

**Comment by ndufresne** [comment]
Figures-out there was a script to install the hooks now, this will save time indeed.

**Comment by ndufresne** [comment]
In short, this change will kind of regress of lot of ffmpeg test, but from there we get the score for the selected HW accelerator, not a mix of that and the software decoder.

**Comment by ndufresne** [comment]
Let me improve the commit message now.

**Review by rgonzalezfluendo — APPROVED** [review]

**Pull request merged**
