### PR TITLE
OCP-2317 : Add AAC reference decoder

### PR DESCRIPTION
**Pull request by mdimopoulos**
+decoder.py: modified decoder() function argument sequence

+aac_dec.py: added a wrapper for the reference aac decoder

+Makefile: changed target names to be more precise and
replaced 2 targets which were not building executables/files
with variables that can be executed at runtime.

### CODE REVIEW

**Review by pamarcos — APPROVED** [review]
Good work, @mdimopoulos!
Please rebase against latest changes in master, push again and good to merge!

**Comment by pamarcos** [comment]
It's good, @mdimopoulos! Just make sure to squash last commit into the other one. Easiest way of doing it is using `git rebase -i master` from your branch and selecting that you want to squash the last commit onto the previous one.

**Comment by mdimopoulos** [comment]
The last step was running for hours :S.
Thanks for the guidance. I see that github provides an automatic squash and merge option, would that work instead?

**Comment by mdimopoulos** [comment]
I did what you suggested, waiting for the tests to complete

**Comment by mdimopoulos** [comment]
Merge done. Fingers crossed for not breaking master

**Pull request merged**
