### PR TITLE
Generate a test suite in fluster for H265 SHVC functionality set

### PR DESCRIPTION
**Pull request by rsanchez87**

### CODE REVIEW

**Review by mdimopoulos — COMMENTED** [review]
Some the changes in the PR cause regressions with the generation of some test suites. I compared the .json files of the repo with the ones generated locally on my machine and i found differences in

`JCT-VC-MV-HEVC.json`, `JVET-VVC_draft6.json`, `JVT-AVC_V1.json`, `JVT-Professional_profiles_V1.json`

Most are related to the checksums themselves, there others too. More details in the related task

**Comment by rsanchez87** [comment]
> Some the changes in the PR cause regressions with the generation of some test suites. I compared the .json files of the repo with the ones generated locally on my machine and i found differences in
> 
> `JCT-VC-MV-HEVC.json`, `JVET-VVC_draft6.json`, `JVT-AVC_V1.json`, `JVT-Professional_profiles_V1.json`
> 
> Most are related to the checksums themselves, there others too. More details in the related task

Ok, thanks, I'm going to check, maybe some change in **find_by_ext** function in this PR

**Comment by rsanchez87** [comment]
> > Some the changes in the PR cause regressions with the generation of some test suites. I compared the .json files of the repo with the ones generated locally on my machine and i found differences in
> > `JCT-VC-MV-HEVC.json`, `JVET-VVC_draft6.json`, `JVT-AVC_V1.json`, `JVT-Professional_profiles_V1.json`
> > Most are related to the checksums themselves, there others too. More details in the related task
> 
> Ok, thanks, I'm going to check, maybe some change in **find_by_ext** function in this PR

[Bug](https://fluendo.atlassian.net/browse/COM-10965?atlOrigin=eyJpIjoiMjQyYzVlMjM4NWNhNDg0NzlkN2Q0OTkzMTE1NTFlYWUiLCJwIjoiaiJ9) created, is not related with this PR

**Review by mdimopoulos — APPROVED** [review]
Looks good to me

**Pull request merged**
