### PR TITLE
Add AV1 reference decoder and test vectors

### PR DESCRIPTION
**Pull request by dwlsalmeida**
Add AV1 reference decoder and test vectors from libaom

### CODE REVIEW

**Review by mdimopoulos — CHANGES_REQUESTED** [review]
Hi @dwlsalmeida and thanks a lot for your contribution.
I've got 2 remarks and change requests
- Could you please rename libaom.py to follow the norm of the rest of the files. av1_aom.py or similar will do
- I saw you provide a script to generate the test list in your comments, this is valuable but no usable within the project as is. Could you please adapt the code taking scripts/gen_jct_vc.py as a guide? Like this we will be able to regenerate the test list easily in case of future changes.

Really appreciate your contribution and help with AV1, thanks a lot

**Comment by dwlsalmeida** [comment]
@mdimopoulos can you check whether this works better for you?

I couldn't really find a way to not invoke aomdec in scripts/gen_av1_aom.py as the *.md5 files are per-frame, i.e.

```f3f3633e25c24e88c2057c4263f10875  av1-1-b8-03-sizedown.mkv-1280x720-0001.i420
f7900a172b47abf17a14f2fb8d4462eb  av1-1-b8-03-sizedown.mkv-1280x720-0002.i420
8e44be70dae5bcee3aa3902027be54f8  av1-1-b8-03-sizedown.mkv-1280x720-0003.i420
4cf4f4eb58a1a0b1eaa27a4cb79330c4  av1-1-b8-03-sizedown.mkv-1280x720-0004.i420
d61b38c688e72126a76812d40ebd982d  av1-1-b8-03-sizedown.mkv-1280x720-0005.i420
0e9f6b0f797737994f4d37e4358d204b  av1-1-b8-03-sizedown.mkv-1280x720-0006.i420
c51a2d765d4f56486c89c5c663aad4a6  av1-1-b8-03-sizedown.mkv-1280x720-0007.i420
86b88efecf34dd7e4bb1d38346bc7a94  av1-1-b8-03-sizedown.mkv-1280x720-0008.i420
02ec4d652fa265cfc928e0bc27ed783a  av1-1-b8-03-sizedown.mkv-1280x720-0009.i420
120e9c7220f1803b796c487a28551382  av1-1-b8-03-sizedown.mkv-1280x720-0010.i420
3f20b55c5cfe25e4b5fec1b295abd383  av1-1-b8-03-sizedown.mkv-352x288-0011.i420
fcc5539f98ed9c51280e46fa77f3c491  av1-1-b8-03-sizedown.mkv-352x288-0012.i420
d9b27a809788b6138774a665d76f8f20  av1-1-b8-03-sizedown.mkv-352x288-0013.i420
c14d7752f71479fcbdb173fa75d29dd5  av1-1-b8-03-sizedown.mkv-352x288-0014.i420
aac95c93e23f67c80dc7946d97ff1504  av1-1-b8-03-sizedown.mkv-352x288-0015.i420
3f3c9a7dcbc316933a68e7c9a0592e3b  av1-1-b8-03-sizedown.mkv-352x288-0016.i420
7ec5e34c09ec2a179ee22c04abad1183  av1-1-b8-03-sizedown.mkv-352x288-0017.i420
f271cda9802563b026274c37a339bade  av1-1-b8-03-sizedown.mkv-352x288-0018.i420
8b889fd48a9466b2dcda52985a5c3695  av1-1-b8-03-sizedown.mkv-352x288-0019.i420
037f485af956ffd97e00ec6c340d7677  av1-1-b8-03-sizedown.mkv-352x288-0020.i420

**Comment by dwlsalmeida** [comment]
By the way, did you request more changes on top of your two written remarks? I may have missed them, I am somewhat unacquainted with Github's UI.

**Comment by rgonzalezfluendo** [comment]
Hi @dwlsalmeida and thanks again for your contribution. It LGTM but I am going to wait until next week for @mdimopoulos to merge it.

**Review by mdimopoulos — APPROVED** [review]
All checks out, thanks a lot for the revision @dwlsalmeida.

**Comment by mdimopoulos** [comment]
There is a pylint issue which we will take a look at separately

**Pull request merged**
