### PR TITLE
COM-4967 Split gstreamer 0.10 and 1.0 logic to remove 0.10 (deprecated)

### PR DESCRIPTION
**Pull request by rsanchez87**

### CODE REVIEW

**Comment by obbardc** [comment]
What's happening to the master branch ?

**Comment by rsanchez87** [comment]
> What's happening to the master branch ?

Hello Christopher, this PR intends to remove everything related to 0.10 in master branch (0.10 is more than 10 years old...)

**Comment by obbardc** [comment]
Makes sense. I thought this was splitting away from master ;-)

**Comment by rsanchez87** [comment]
> Makes sense. I thought this was splitting away from master ;-)

I have updated the name of the PR for more clarity, it wasn't very descriptive really, thanks!

**Review by mdimopoulos — CHANGES_REQUESTED** [review]
All else looks good to me!

**Review by mdimopoulos — APPROVED** [review]

**Comment by rsanchez87** [comment]
> By the way i had completely forgotten about `pyproject.toml`, could you add all the missing test suites in the section [tool.setuptools.data-files]
> 
> All else looks good to me!

I'm going to add these ts in the task if you see it well:

https://fluendo.atlassian.net/browse/COM-10938

**Pull request merged**
